xcodebuild output handling
MarathonLabs/marathon pull request #151
Opened 2019-01-08 05:12 UTC by memega

- redesigned handling of remote command output, introducing timeout interruption;
- improved coroutines support with accurate structure;
- after a test run failure, simulator provider attempts to reuse the same simulator
- updated the sample app;
- added custom log configuraton;
- added a shutdown hook to print timeline summary even when execution is interrupted.

2019-01-30 11:38 UTC, Malinskiy requested changes

2019-01-30 11:38 UTC, Malinskiy commented on cli/src/main/kotlin/com/malinskiy/marathon/cli/args/FileConfiguration.kt
> +        var timeoutMillis: Long?,
Can we create a more meaningful name? I suspect this is the whole run timeout

2019-01-30 11:38 UTC, Malinskiy commented on cli/src/main/kotlin/com/malinskiy/marathon/cli/args/FileIOSConfiguration.kt
> +        @JsonProperty("teamcityCheckoutDir") val teamcityCheckoutDir: File? = null,
We should not depend on the TeamCity in the marathon. And marathon can also be executed locally. Let's rename this as well

2019-01-30 11:38 UTC, Malinskiy commented on cli/src/main/kotlin/com/malinskiy/marathon/cli/args/MarathonCliConfiguration.kt
> -    val androidSdkDir: File? by parser
:+1:

2019-01-30 11:38 UTC, Malinskiy commented on core/src/main/kotlin/com/malinskiy/marathon/analytics/tracker/remote/influx/InfluxDbTracker.kt
> +                .tag("run", InfluxDbTracker.runUUID)
This is high cardinality tag. I'm not sure we want to make it a tag.

2019-01-30 11:38 UTC, Malinskiy commented on core/src/main/kotlin/com/malinskiy/marathon/execution/device/DeviceAction.kt
> +    data class NotifyIsReady(val result: CompletableDeferred<TestBatchResults>? = null) : DeviceAction()
:+1:

2019-01-30 11:38 UTC, Malinskiy commented on core/src/main/kotlin/com/malinskiy/marathon/execution/DevicePoolActor.kt
> +        val shuffledDevices = devices.values
Can we use sequences? https://blog.kotlin-academy.com/effective-kotlin-use-sequence-for-bigger-collections-with-more-than-one-processing-step-649a15bb4bf

2019-01-30 11:38 UTC, Malinskiy commented on vendor/vendor-ios/src/main/kotlin/com/malinskiy/marathon/ios/device/LocalListSimulatorProvider.kt
> +private const val MAX_SERIAL = 8
The purpose is unclear. Please rename

2019-01-31 02:45 UTC, tagantroy commented on core/src/main/kotlin/com/malinskiy/marathon/analytics/tracker/remote/influx/InfluxDbTracker.kt
> +                .tag("run", InfluxDbTracker.runUUID)
> fields are not indexed. tags are indexed.

2019-01-31 08:35 UTC, memega commented on cli/src/main/kotlin/com/malinskiy/marathon/cli/args/FileIOSConfiguration.kt
> +        @JsonProperty("teamcityCheckoutDir") val teamcityCheckoutDir: File? = null,
First of all, this is an optional value; secondly, it is used _only_ to produce teamcity service messages

2019-01-31 11:26 UTC, memega commented on cli/src/main/kotlin/com/malinskiy/marathon/cli/args/FileConfiguration.kt
> +        var timeoutMillis: Long?,
That would be a single command execution timeout

2019-01-31 11:29 UTC, memega commented on core/src/main/kotlin/com/malinskiy/marathon/analytics/tracker/remote/influx/InfluxDbTracker.kt
> +                .tag("run", InfluxDbTracker.runUUID)
Removed it altogether

2019-01-31 11:29 UTC, memega commented on cli/src/main/kotlin/com/malinskiy/marathon/cli/args/FileIOSConfiguration.kt
> +        @JsonProperty("teamcityCheckoutDir") val teamcityCheckoutDir: File? = null,
Removed it along with unfinished logarchive collecting feature

2019-02-10 16:09 UTC, merged