Add uncompleted tests retry quota
MarathonLabs/marathon pull request #247
Opened 2019-07-04 13:58 UTC by lukaville

Fixes #243 by `uncompletedTestRetryQuota` configuration option. By default, it has the same behavior as now (infinitely re-runs uncompleted tests)

2019-07-16 10:01 UTC, Malinskiy requested changes

2019-07-16 10:01 UTC, Malinskiy commented on core/src/main/kotlin/com/malinskiy/marathon/execution/queue/QueueActor.kt
> +        val (failedUncompletedTests, uncompleted) = results.uncompleted.partition {
Can we improve the naming here? Next thing is to add uncompletedFailed and it will become completely unreadable :(

2019-07-16 10:37 UTC, lukaville commented on core/src/main/kotlin/com/malinskiy/marathon/execution/queue/QueueActor.kt
> +        val (failedUncompletedTests, uncompleted) = results.uncompleted.partition {
Changed `failedUncompletedTests` to `uncompletedRetryQuotaExceeded`

2019-08-02 14:36 UTC, tagantroy commented
@Malinskiy Comments are resolved. Should we merge it?

2019-08-03 02:15 UTC, Malinskiy commented
@tagantroy merging for now, but I'd like to later move this into retry strategy since it's actually part of that config.

2019-08-03 02:16 UTC, merged