Close bugsnag at the end to prevent hanging due internal thread pool
MarathonLabs/marathon pull request #309
Opened 2020-01-08 17:55 UTC by BorisOsipov

Fixed #307

2020-01-09 02:43 UTC, Vacxe approved these changes

2020-01-11 07:12 UTC, Malinskiy requested changes

2020-01-11 07:12 UTC, Malinskiy commented on cli/src/main/kotlin/com/malinskiy/marathon/cli/ApplicationView.kt
> +        bugsnagExceptionsReporter.end()
please add the same to com/malinskiy/marathon/MarathonRunTask.kt:90

2020-01-11 09:08 UTC, Malinskiy commented
@BorisOsipov  :+1:

2020-01-13 00:18 UTC, Malinskiy approved these changes

2020-01-13 01:58 UTC, merged